INFO: [guild] Running trial d85dffa00f7248d1be197fe1bfa32cb7: TABL:train (attention_constraint=None, attention_regularizer=None, binarize=no, dev=no, dimensionality=100, horizon=1, learning_rate=0.001, n_bl_layers=2, n_tabl_layers=1, optimizer=adam, projection_constraint=None, projection_regularizer=None, remote=no, window=100)
Traceback (most recent call last):
  File "/home/blez/Projects/anomaly_simulation/Zoo/Results/runs/d85dffa00f7248d1be197fe1bfa32cb7/.guild/sourcecode/TABL/train.py", line 78, in <module>
    _, train_y, _, test_y, train_generator, test_generator = aursad.get_dataset_generator(path=data_path,
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/aursad.py", line 190, in get_dataset_generator
    data = load_dataset(path=path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/utils.py", line 166, in load_dataset
    dataframe = pd.read_hdf(path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File AURSAD.h5 does not exist
ERROR: [guild] Trial d85dffa00f7248d1be197fe1bfa32cb7 exited with an error (1) - see log for details
INFO: [guild] Running trial c7ed98cb728440fc8f2ac5c3caa28e34: TABL:train (attention_constraint=None, attention_regularizer=None, binarize=no, dev=no, dimensionality=80, horizon=1, learning_rate=0.001, n_bl_layers=2, n_tabl_layers=1, optimizer=adam, projection_constraint=None, projection_regularizer=None, remote=no, window=100)
Traceback (most recent call last):
  File "/home/blez/Projects/anomaly_simulation/Zoo/Results/runs/c7ed98cb728440fc8f2ac5c3caa28e34/.guild/sourcecode/TABL/train.py", line 78, in <module>
    _, train_y, _, test_y, train_generator, test_generator = aursad.get_dataset_generator(path=data_path,
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/aursad.py", line 190, in get_dataset_generator
    data = load_dataset(path=path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/utils.py", line 166, in load_dataset
    dataframe = pd.read_hdf(path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File AURSAD.h5 does not exist
ERROR: [guild] Trial c7ed98cb728440fc8f2ac5c3caa28e34 exited with an error (1) - see log for details
INFO: [guild] Running trial e0a20b6b19eb4e71a239ade5a56efbd8: TABL:train (attention_constraint=None, attention_regularizer=None, binarize=no, dev=no, dimensionality=40, horizon=1, learning_rate=0.001, n_bl_layers=2, n_tabl_layers=1, optimizer=adam, projection_constraint=None, projection_regularizer=None, remote=no, window=100)
Traceback (most recent call last):
  File "/home/blez/Projects/anomaly_simulation/Zoo/Results/runs/e0a20b6b19eb4e71a239ade5a56efbd8/.guild/sourcecode/TABL/train.py", line 78, in <module>
    _, train_y, _, test_y, train_generator, test_generator = aursad.get_dataset_generator(path=data_path,
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/aursad.py", line 190, in get_dataset_generator
    data = load_dataset(path=path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/utils.py", line 166, in load_dataset
    dataframe = pd.read_hdf(path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File AURSAD.h5 does not exist
ERROR: [guild] Trial e0a20b6b19eb4e71a239ade5a56efbd8 exited with an error (1) - see log for details
