Traceback (most recent call last):
  File "/home/blez/Projects/anomaly_simulation/Zoo/Results/runs/e0a20b6b19eb4e71a239ade5a56efbd8/.guild/sourcecode/TABL/train.py", line 78, in <module>
    _, train_y, _, test_y, train_generator, test_generator = aursad.get_dataset_generator(path=data_path,
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/aursad.py", line 190, in get_dataset_generator
    data = load_dataset(path=path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/aursad/utils.py", line 166, in load_dataset
    dataframe = pd.read_hdf(path)
  File "/home/blez/anaconda3/envs/anomaly_detection/lib/python3.8/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File AURSAD.h5 does not exist
